{{ config_model_iceberg_strategy() }}

select   
    dim_ct."Contact_key",
    dim_ct."Id_Contact",
    dim_ct."Account_ID", 
    dim_ct."Individual_ID",
    dim_ct."Campain_Context /Campaign name",
    dim_ct."Country",
    dim_ct."Request_Type",
    dim_ct."FormSubmittedDate",
    dim_ct."Language",
    dim_ct."Origin_URL",
    dim_ct."Email",
    fact_mk.id_marketing,
    fact_mk."et4ae5_NumberOfTotalClicks_c__c",
    fact_mk."Email_DateUnsubscribed",
    fact_mk."cdp_sys_PartitionDate__c",
    fact_mk."DataSourceObject__c",
    fact_mk."Content_block",
    fact_mk."et4ae5_MergeId_c__c",
    fact_mk."et4ae5_FromName_c__c",
    fact_mk."SystemModstamp__c",
    fact_mk."et4ae5_Email_ID_c__c",
    fact_mk."et4ae5_TriggeredSendDefinitionName_c__c",
    fact_mk."Contact_ID",
    fact_mk."et4ae5_DMTrackingId_c__c",
    fact_mk."Content_topic",
    fact_mk."KQ_Id__c",
    fact_mk."Email_DateBounced",
    fact_mk."LastModifiedById__c",
    fact_mk."Email_Opened",
    fact_mk."IsDeleted__c",
    fact_mk."et4ae5_BatchId_c__c",
    fact_mk."et4ae5_Email_Asset_ID_c__c",
    fact_mk."et4ae5_Tracking_As_Of_c__c",
    fact_mk."et4ae5_CampaignMemberId_c__c",
    fact_mk."Email_Date_Sent",
    fact_mk."Email_Clicked",
    fact_mk."Name__c",
    fact_mk."et4ae5_FromAddress_c__c",
    fact_mk."SfdcOrganizationId__c",
    fact_mk."Email_UniqueClicks",
    fact_mk."et4ae5_Email_c__c",
    fact_mk."Email_Date_Opened",
    fact_mk."Email_HardBounce",
    fact_mk."CreatedDate__c",
    fact_mk."cdp_sys_SourceVersion__c",
    fact_mk."LastModifiedDate__c",
    fact_mk."DataSource__c",
    fact_mk."et4ae5_SubscriberId_c__c",
    fact_mk."OwnerId__c",
    fact_mk."et4ae5_JobId_c__c",
    fact_mk."Email_SoftBounce",
    fact_mk."et4ae5_Lead_c__c",
    fact_mk."et4ae5_TriggeredSendDefinition_c__c",
    fact_mk."et4ae5_Contact_c__c",
    fact_mk."et4ae5_ListId_c__c",
    fact_mk."IndividualEmailResult_ID",
    fact_mk."et4ae5_Lead_ID_c__c",
    fact_mk."CreatedById__c",
    cast(current_timestamp() as TIMESTAMP_NTZ(6)) as process_ingestion_date
from {{ ref('stg_individualemailresult_rsg') }} fact_mk
left join {{ ref('stg_dim_contact_rsg') }} dim_ct
    on fact_mk."Contact_ID" = dim_ct."Contact_key"
{% if is_incremental() %}
WHERE fact_mk."LastModifiedDate__c" >= (select max("LastModifiedDate__c") from {{ this }})
{% endif %}
