{{ config_model_iceberg_strategy(
    materialized_type="incremental",
    unique_key="ContactPoint_key",
    incremental_strategy="merge"
) }}

SELECT
    "LastReferencedDate__c",
    "PrivacyConsentStatus__c",
    "PartyRoleId__c",
    "Id__c" as "ContactPoint_key",
    {{ dbt_utils.generate_surrogate_key(['"Id__c"']) }} AS "Id_ContactPoint",
    "cdp_sys_PartitionDate__c",
    "RSG_Consent_Status_c__c" as "Consent_Status",
    "CreatedById__c",
    "ContactPointType__c",
    "CaptureSource__c",
    "PartyId__c",
    "Name__c" as "ChannelA",
    "LastModifiedDate__c",
    "CVP_Initial_Capture_Date_c__c",
    "DataUsePurposeId__c",
    "KQ_Id__c",
    "SystemModstamp__c",
    "LastModifiedById__c",
    "LastViewedDate__c",
    "BusinessBrandId__c",
    "DataSource__c",
    "RSG_Archived_c__c",
    "SfdcOrganizationId__c",
    "EffectiveFrom__c",
    "EngagementChannelTypeId__c",
    "RSG_Purpose_c__c" as "Purpose",
    "CaptureDate__c",
    "CreatedDate__c",
    "RSG_Contact_Point_Type_c__c" as "ChannelB",
    "DataSourceObject__c",
    "EffectiveTo__c",
    "cdp_sys_SourceVersion__c",
    "CaptureContactPointType__c",
    "OwnerId__c",
    "IsDeleted__c",
    "DoubleConsentCaptureDate__c",    
    cast(current_timestamp() as TIMESTAMP_NTZ(6)) as process_ingestion_date
FROM {{ source("CRM", "CONTACTPOINTTYPECONSENT_RSG") }}
