{{ config_model_iceberg_strategy(
    materialized_type="incremental",
    unique_key="Contact_key",
    incremental_strategy="merge"
) }}

SELECT
    "CVP_Nationality_c__c",
    "LastReferencedDate__c",
    "CVP_Monthly_Newsletter_c__c",
    "RES_National_ID_Passport_c__c",
    "RSG_Assistant_c__c",
    "CVP_Customer_Status_c__c",
    "CVP_Active_Interests_c__c",
    "Id__c" AS "Contact_key",
    {{ dbt_utils.generate_surrogate_key(['"Id__c"']) }} AS "Id_Contact",
    "Phone__c",
    "RSG_PreferredContactMethod_c__c",
    "RecordTypeId__c",
    "CVP_Mobile_Verified_c__c",
    "LastCUUpdateDate__c",
    "EmailBouncedReason__c",
    "Suffix__c",
    "CVP_Mobile_Number_c__c",
    "KQ_Email__c",
    "Jigsaw__c",
    "LastModifiedById__c",
    "OtherLatitude__c",
    "CVP_Country_of_Residence_c__c" AS "Country",
    "CreatedDate__c",
    "IsPersonAccount__c",
    "CVP_Mobile_Not_Verified_c__c",
    "DoNotCall__c",
    "LastName__c",
    "CVP_UTM_Source_c__c",
    "RSG_CustomerPriority_c__c",
    "MailingCountry__c",
    "DataSourceObject__c",
    "CVP_Source_Delete_c__c",
    "CVP_Marital_Status_c__c",
    "CVP_Citizenship_c__c",
    "RSG_Nationality_c__c",
    "Fax__c",
    "RSG_Company_Name_c__c",
    "RSG_InterestedInAmaala_c__c",
    "Pronouns__c",
    "GenderIdentity__c",
    "OtherCountry__c",
    "Description__c",
    "LeadSource__c" AS "LeadSource",
    "DataSource__c",
    "Salutation__c",
    "CVP_Country_Code_c__c",
    "CVP_EmailHasCompletedWelcomeJourney_c__c",
    "SystemModstamp__c",
    "EmailBouncedDate__c",
    "OtherStreet__c",
    "MobilePhone__c",
    "IsDeleted__c",
    "MailingCity__c",
    "FirstName__c",
    "RES_Contact_ID_c__c",
    "LastCURequestDate__c",
    "OtherState__c",
    "RES_Designation_c__c",
    "CVP_Currency_c__c",
    "RSG_Asst_Phone_c__c",
    "RSG_Marketing_Consent_Provided_c__c",
    "OtherCity__c",
    "AssistantPhone__c",
    "CVP_is_Visitor_Account_Deleted_c__c",
    "LastModifiedDate__c",
    "ContactSource__c",
    "Name__c",
    "SfdcOrganizationId__c",
    "MasterRecordId__c",
    "OtherPostalCode__c",
    "CVP_UTM_Medium_c__c",
    "JigsawContactId__c",
    "IndividualId__c" AS "Individual_ID",
    "cdp_sys_SourceVersion__c",
    "RSG_NotSendMigration_Mce_c__c",
    "RES_Contact_Record_Name_c__c",
    "MiddleName__c",
    "HasOptedOutOfFax__c",
    "CVP_Red_Sea_Experience_c__c",
    "CVP_Languages_Spoken_c__c" AS "Language",
    "LastActivityDate__c",
    "CVP_Email_Verified_c__c",
    "ReportsToId__c",
    "RSG_Travelling_From_c__c",
    "CVP_Referral_URL_c__c",
    "AccountId__c" AS "Account_ID",
    "KQ_Id__c",
    "et4ae5_HasOptedOutOfMobile_c__c",
    "CVP_Enquiry_Type_c__c" AS "Request_Type",
    "CVP_Resort_Exclusive_Offers_c__c",
    "AssistantName__c",
    "CVP_UTM_Campaign_c__c",
    "CVP_FormSubmittedDate_c__c" AS "FormSubmittedDate",
    "CVP_Campaign_Name_c__c" AS "Campain_Context /Campaign name",
    "MailingPostalCode__c",
    "MailingStreet__c",
    "CVP_Gender_c__c",
    "Email__c" AS "Email",
    "OtherLongitude__c",
    "HasOptedOutOfEmail__c",
    "Birthdate__c",
    "RSG_External_Id_c__c",
    "PhotoUrl__c",
    "OwnerId__c",
    "OtherPhone__c",
    "CVP_Sync_with_Travel_Studio_c__c",
    "MailingLatitude__c",
    "KQ_IndividualId__c",
    "RSG_Language_c__c",
    "OtherGeocodeAccuracy__c",
    "CVP_Latest_Interaction_URL_c__c",
    "RES_Account_Tier_c__c",
    "CVP_Ping_Identity_Status_c__c",
    "CVP_Landing_URL_c__c",
    "IsEmailBounced__c",
    "CreatedById__c",
    "Title__c",
    "CVP_Origin_URL_c__c" AS "Origin_URL",
    "CVP_Status_Visitor_Account_c__c",
    "MailingGeocodeAccuracy__c",
    "HomePhone__c",
    "Department__c",
    "RSG_InterestedInRedSea_c__c",
    "et4ae5_Mobile_Country_Code_c__c",
    "CVP_Private_Residences_c__c",
    "LastViewedDate__c",
    "RSG_Testing_Mce_c__c",
    "CVP_Email_Not_Verified_c__c",
    "MailingLongitude__c",
    "BuyerAttributes__c",
    "MailingState__c",
    cast(current_timestamp() as TIMESTAMP_NTZ(6)) as process_ingestion_date
FROM {{ source("CRM", "CONTACT_RSG") }}
