{{ iceberg_model_config(
    materialized_type="incremental", 
    unique_key=["BOOKING_ID", "SERVICE_ID", "OPTION_ID", "SNAPSHOT_DATE"], 
    incremental_strategy="merge"
) }}

WITH booked_services AS (
SELECT BOOKINGID ,
    BOOKEDSERVICEID,
        SERVICEID,
    INGESTION_TIMESTAMP::DATE AS SNAPSHOT_DATE
FROM {{ source('TS', 'BOOKED_SERVICE_DETAILS') }}
WHERE INGESTION_TIMESTAMP IS NOT NULL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY  BOOKEDSERVICEID , DATE_TRUNC('DAY', INGESTION_TIMESTAMP)
    ORDER BY INGESTION_TIMESTAMP DESC
) = 1
)
, booked_options AS (

    SELECT BOOKEDSERVICEID,
           BOOKEDOPTIONID,
           SERVICEOPTIONINSERVICEID,
           INGESTION_TIMESTAMP::DATE AS SNAPSHOT_DATE
    FROM {{ source('TS', 'BOOKED_OPTION_DETAILS') }}
    WHERE BOOKEDOPTIONID IS NOT NULL
    AND INGESTION_TIMESTAMP IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY BOOKEDOPTIONID, DATE_TRUNC('DAY', INGESTION_TIMESTAMP)
        ORDER BY INGESTION_TIMESTAMP DESC
    ) = 1

)


SELECT 
    DISTINCT(bo.BOOKEDOPTIONID) AS BOOKED_OPTION_ID,
    bo.SERVICEOPTIONINSERVICEID AS OPTION_ID,
    bs.BOOKEDSERVICEID AS BOOKED_SERVICE_ID,
    bs.SERVICEID AS SERVICE_ID, 
    bs.BOOKINGID AS BOOKING_ID,
    bs.SNAPSHOT_DATE,
    DENSE_RANK () OVER (
        PARTITION BY BOOKING_ID
        ORDER BY SNAPSHOT_DATE DESC
    ) AS SNAPSHOT_RANK
FROM booked_services bs
LEFT JOIN booked_options bo
USING(BOOKEDSERVICEID, SNAPSHOT_DATE)

{% if is_incremental() %}
WHERE bs.SNAPSHOT_DATE > (SELECT MAX(SNAPSHOT_DATE) FROM {{ this }})
{% endif %}
