{{ iceberg_model_config() }}

WITH unique_status AS (
    SELECT 
        DISTINCT(BOOKINGSTATUSNAME) AS STATUS_NAME,
        CASE 
            WHEN UPPER(BOOKINGSTATUSNAME) LIKE '%CANCEL%' THEN TRUE 
            ELSE FALSE 
        END AS IS_CANCELLATION,
        HASH(BOOKINGSTATUSNAME) AS STATUS_ID
    FROM {{ source('TS', 'BOOKING_HEADER_DETAILS') }}
    WHERE BOOKINGSTATUSID IS NOT NULL
)
SELECT 
    STATUS_ID,
    STATUS_NAME,
    IS_CANCELLATION
FROM unique_status