{{ iceberg_model_config(
    materialized_type="incremental", 
    unique_key=["BOOKING_ID", "SNAPSHOT_DATE"],
    incremental_strategy="merge"
) }}

WITH booking_header AS (
    SELECT 
        BOOKINGID::INT                   AS BOOKING_ID,
        "BookingReferenceNumber"         AS BOOKING_REFERENCE_NUMBER,
        BOOKINGBOOKINGDATE::DATE         AS BOOKING_DATE,
        BOOKINGSTARTDATE::DATE           AS BOOKING_START_DATE,
        BOOKINGENDDATE::DATE             AS BOOKING_END_DATE,
        SMCPASSENGERID                   AS SMC_PASSENGER_ID,
        CURRENCYISOCODE                  AS CURRENCY_CODE,
        NOOFNIGHTS                       AS NUMBER_OF_NIGHTS,
        HASH(AGENCYTYPENAME)             AS SEGMENT_ID , 
        HASH(BOOKINGSTATUSNAME)          AS STATUS_ID , 
        HASH(origintypename)             AS CHANNEL_ID ,
        CASE 
            WHEN COUNT(DISTINCT bookingid) OVER (PARTITION BY smcpassengerid) > 1 
            THEN TRUE 
            ELSE FALSE
        END AS IS_REPEAT_GUEST,
        CASE 
            WHEN BOOKINGBOOKINGDATE IS NOT NULL AND BOOKINGSTARTDATE IS NOT NULL
            THEN DATEDIFF(day, DATE(BOOKINGBOOKINGDATE), DATE(BOOKINGSTARTDATE))
            ELSE NULL
        END AS LEAD_TIME_DAYS,
        CASE 
            WHEN UPPER(COALESCE(BOOKINGSTATUSNAME, '')) LIKE '%CANCEL%' 
            THEN TRUE 
            ELSE FALSE 
        END AS IS_CANCELLED,
        CAST(DATE_TRUNC('DAY', INGESTION_TIMESTAMP) AS DATE) AS SNAPSHOT_DATE

    FROM {{ source('TS', 'BOOKING_HEADER_DETAILS') }}
    WHERE INGESTION_TIMESTAMP IS NOT NULL 
    QUALIFY ROW_NUMBER() OVER (
            PARTITION BY BOOKINGID, DATE_TRUNC('DAY', INGESTION_TIMESTAMP)
            ORDER BY INGESTION_TIMESTAMP DESC
        ) = 1 
    ORDER BY 1 , ingestion_timestamp
)

,booking_finance AS (
        SELECT 
            BOOKINGID, 
            CAST(COALESCE(f.BOOKAMOUNT, 0) AS NUMBER(30,2))         AS BOOKING_AMOUNT,
            CAST(COALESCE(f.SELLAMOUNT, 0) AS NUMBER(30,2))         AS SELLING_AMOUNT,
            CAST(COALESCE(f.MARGINAMOUNT, 0) AS NUMBER(30,2))       AS MARGIN_AMOUNT,
            CAST(COALESCE(f.MARGINPERCENT, 0) AS NUMBER(30,2))      AS MARGIN_PERCENT,
            CAST(DATE_TRUNC('DAY', f.INGESTION_TIMESTAMP) AS DATE)  AS SNAPSHOT_DATE
        FROM {{ source('TS', 'BOOKING_FINANCE_DATA') }} f
         QUALIFY ROW_NUMBER() OVER (
                PARTITION BY f.BOOKINGID, DATE_TRUNC('DAY', f.INGESTION_TIMESTAMP)
                ORDER BY f.INGESTION_TIMESTAMP DESC
            ) = 1 
)
, booked_services_filtered AS (
    SELECT BOOKINGID,
           SERVICETYPENAME,
           BOOKEDSERVICEID,
           INGESTION_TIMESTAMP
    FROM {{ source('TS', 'BOOKED_SERVICE_DETAILS') }}
    QUALIFY ROW_NUMBER() OVER (
            PARTITION BY BOOKEDSERVICEID, DATE_TRUNC('DAY', INGESTION_TIMESTAMP)
            ORDER BY INGESTION_TIMESTAMP DESC
        ) = 1

)
, booked_services_aggregated AS (
SELECT 
    BOOKINGID, 
    COUNT(DISTINCT CASE 
        WHEN LOWER(SERVICETYPENAME) LIKE '%accommodation%' 
        THEN BOOKEDSERVICEID 
    END) AS NUMBER_OF_ACCOMMODATION_SERVICES,
    COUNT(DISTINCT CASE 
        WHEN LOWER(SERVICETYPENAME) LIKE '%mobility%' 
        THEN BOOKEDSERVICEID 
    END) AS NUMBER_OF_MOBILITY_SERVICES,
    COUNT(DISTINCT CASE 
        WHEN LOWER(SERVICETYPENAME) LIKE '%experience%' 
        THEN BOOKEDSERVICEID 
    END) AS NUMBER_OF_EXPERIENCE_SERVICES, 
    CAST(DATE_TRUNC('DAY', INGESTION_TIMESTAMP) AS DATE) AS SNAPSHOT_DATE
FROM booked_services_filtered
GROUP BY BookingID, SNAPSHOT_DATE 
)


, booked_passengers AS (
    SELECT 
        BOOKINGID,
        PASSENGERID,
        CAST(DATE_TRUNC('DAY', INGESTION_TIMESTAMP) AS DATE) AS SNAPSHOT_DATE
    FROM {{ source('TS', 'BOOKED_PASSENGERS') }}
    QUALIFY ROW_NUMBER() OVER (
            PARTITION BY BookingID, PASSENGERID, DATE_TRUNC('DAY', INGESTION_TIMESTAMP)
            ORDER BY INGESTION_TIMESTAMP DESC
        ) = 1 
), booked_passengers_aggregated AS (
    SELECT COUNT(DISTINCT(PASSENGERID)) NUMBER_OF_GUESTS,
            BOOKINGID,
            SNAPSHOT_DATE, 
    FROM booked_passengers
    GROUP BY BOOKINGID ,SNAPSHOT_DATE
)

, destination_lookup AS (
    SELECT 
        BOOKINGID,
        md5_binary(REGIONNAME) AS DESTINATION_ID,
        CAST(DATE_TRUNC('DAY', INGESTION_TIMESTAMP) AS DATE) AS SNAPSHOT_DATE
    FROM {{ source('TS', 'BOOKED_SERVICE_DETAILS') }}
    WHERE REGIONNAME IS NOT NULL
    AND INGESTION_TIMESTAMP IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY BOOKINGID, DATE_TRUNC('DAY', INGESTION_TIMESTAMP)
        ORDER BY INGESTION_TIMESTAMP DESC
    ) = 1
)

, country_lookup AS (
    SELECT 
        BOOKINGID,
        COUNTRYID AS COUNTRY_ID,
        CAST(DATE_TRUNC('DAY', INGESTION_TIMESTAMP) AS DATE) AS SNAPSHOT_DATE
    FROM {{ source('TS', 'BOOKED_PASSENGERS') }}
    WHERE COUNTRYID IS NOT NULL
    AND INGESTION_TIMESTAMP IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY BOOKINGID, DATE_TRUNC('DAY', INGESTION_TIMESTAMP)
        ORDER BY INGESTION_TIMESTAMP DESC
    ) = 1
)

, finance_aggregated AS (
    SELECT 
        sf.BOOKEDSERVICEID,
        sf.BOOKINGID,
        sf.INGESTION_TIMESTAMP,
        CAST(DATE_TRUNC('DAY', sf.INGESTION_TIMESTAMP) AS DATE) AS SNAPSHOT_DATE,
        SUM(
            COALESCE(TRY_CAST(SELLINGAMOUNT AS FLOAT), 0) + 
            COALESCE(TRY_CAST(SELLTAX AS FLOAT), 0)
        ) OVER (
            PARTITION BY BOOKINGID, BOOKEDSERVICEID, INGESTION_TIMESTAMP
        ) AS TOTAL_AMOUNT
    FROM {{ source('TS', 'BOOKEDSERVICES_FINANCE_DATA') }} sf
    WHERE sf.BOOKEDSERVICEID IS NOT NULL
      AND sf.INGESTION_TIMESTAMP IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY BOOKINGID, BOOKEDSERVICEID, DATE_TRUNC('DAY', INGESTION_TIMESTAMP) 
        ORDER BY INGESTION_TIMESTAMP DESC
    ) = 1
)
, service_aggregated AS (
    SELECT 
        bsd.BOOKINGID,
        CAST(DATE_TRUNC('DAY', bsd.INGESTION_TIMESTAMP) AS DATE) AS SNAPSHOT_DATE,
        CASE 
            WHEN LOWER(bsd.SERVICETYPENAME) LIKE '%accommodation%' THEN 'accommodation'
            WHEN LOWER(bsd.SERVICETYPENAME) LIKE '%mobility%' THEN 'mobility'
            WHEN LOWER(bsd.SERVICETYPENAME) LIKE '%experience%' THEN 'experience'
            ELSE 'other'
        END AS service_category,
        COALESCE(f.TOTAL_AMOUNT, 0) AS TOTAL_AMOUNT
    FROM booked_services_filtered bsd
    INNER JOIN finance_aggregated f 
        ON bsd.BOOKEDSERVICEID = f.BOOKEDSERVICEID
        AND CAST(DATE_TRUNC('DAY', bsd.INGESTION_TIMESTAMP) AS DATE) = f.SNAPSHOT_DATE
    WHERE bsd.BOOKINGID IS NOT NULL
      AND bsd.INGESTION_TIMESTAMP IS NOT NULL
      AND bsd.BOOKEDSERVICEID IS NOT NULL
)

, sub_total AS (
    SELECT 
        BOOKINGID,
        SNAPSHOT_DATE,
        COALESCE(SUM(CASE WHEN service_category = 'accommodation' THEN TOTAL_AMOUNT END), 0) AS SUBTOTAL_ACCOMMODATION,
        COALESCE(SUM(CASE WHEN service_category = 'mobility' THEN TOTAL_AMOUNT END), 0) AS SUBTOTAL_MOBILITY,
        COALESCE(SUM(CASE WHEN service_category = 'experience' THEN TOTAL_AMOUNT END), 0) AS SUBTOTAL_EXPERIENCE
    FROM service_aggregated
    GROUP BY BOOKINGID, SNAPSHOT_DATE
)

SELECT 
    bh.BOOKING_ID,
    bh.BOOKING_REFERENCE_NUMBER,
    bh.BOOKING_DATE,
    bh.BOOKING_START_DATE,
    bh.BOOKING_END_DATE,
    bh.SMC_PASSENGER_ID,
    bh.SEGMENT_ID,
    bh.STATUS_ID,
    bh.CHANNEL_ID,
    dl.DESTINATION_ID,
    cl.COUNTRY_ID,
    bh.CURRENCY_CODE,
    bf.BOOKING_AMOUNT,
    bf.SELLING_AMOUNT,
    bf.MARGIN_AMOUNT,
    bf.MARGIN_PERCENT,
    bp.NUMBER_OF_GUESTS,
    bh.NUMBER_OF_NIGHTS,
    bs.NUMBER_OF_ACCOMMODATION_SERVICES,
    bs.NUMBER_OF_MOBILITY_SERVICES,
    bs.NUMBER_OF_EXPERIENCE_SERVICES,
    st.SUBTOTAL_ACCOMMODATION,
    st.SUBTOTAL_MOBILITY,
    st.SUBTOTAL_EXPERIENCE,
    bh.IS_REPEAT_GUEST,
    bh.LEAD_TIME_DAYS,
    bh.IS_CANCELLED,
    bh.SNAPSHOT_DATE
FROM booking_header bh
LEFT JOIN booking_finance bf
ON bh.BOOKING_ID = bf.BOOKINGID
AND bh.SNAPSHOT_DATE = bf.SNAPSHOT_DATE
LEFT JOIN booked_services_aggregated bs
ON bh.BOOKING_ID = bs.BOOKINGID
AND bh.SNAPSHOT_DATE = bs.SNAPSHOT_DATE
LEFT JOIN  booked_passengers_aggregated bp
ON bh.BOOKING_ID = bp.BOOKINGID
AND bh.SNAPSHOT_DATE = bp.SNAPSHOT_DATE
LEFT JOIN destination_lookup dl
ON bh.BOOKING_ID = dl.BOOKINGID
AND bh.SNAPSHOT_DATE = dl.SNAPSHOT_DATE
LEFT JOIN country_lookup cl
ON bh.BOOKING_ID = cl.BOOKINGID
AND bh.SNAPSHOT_DATE = cl.SNAPSHOT_DATE
LEFT JOIN sub_total st
ON bh.BOOKING_ID = st.BOOKINGID
AND bh.SNAPSHOT_DATE = st.SNAPSHOT_DATE

{% if is_incremental() %}
WHERE CAST(bh.SNAPSHOT_DATE AS DATE) > (SELECT MAX(SNAPSHOT_DATE) FROM {{ this }})
{% endif %}
