{{ iceberg_model_config(
    materialized_type="incremental", 
    unique_key=["SMC_PASSENGER_ID","INGESTION_TIMESTAMP"], 
    incremental_strategy="merge"
) }}

WITH passenger_changes AS (
    SELECT 
        SMCPASSENGERID,
        PASSENGERID,
        PASSENGERFIRSTNAME,
        PASSENGERLASTNAME,
        PASSENGERAGE,
        ADDRESSEMAILADDRESS,
        PASSENGERISLEADPASSENGER,
        PASSENGERTYPENAME,
        NATIONALITYTYPENAME,
        INGESTION_TIMESTAMP
    FROM {{ source('TS', 'BOOKED_PASSENGERS') }}
    WHERE
        SMCPASSENGERID IS NOT NULL

      AND PASSENGERISLEADPASSENGER = TRUE
      AND INGESTION_TIMESTAMP IS NOT NULL
        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY SMCPASSENGERID,
                PASSENGERID,
                PASSENGERFIRSTNAME,
                PASSENGERLASTNAME,
                PASSENGERAGE,
                ADDRESSEMAILADDRESS,
                PASSENGERISLEADPASSENGER,
                PASSENGERTYPENAME,
                NATIONALITYTYPENAME
            ORDER BY
                INGESTION_TIMESTAMP
        ) = 1
)
SELECT  
    SMCPASSENGERID  AS SMC_PASSENGER_ID,
    CAST(PASSENGERID AS VARCHAR(100)) AS PASSENGER_ID,
    CAST(PASSENGERFIRSTNAME AS VARCHAR(100)) AS FIRST_NAME,
    CAST(PASSENGERLASTNAME AS VARCHAR(100)) AS LAST_NAME,
    CAST(PASSENGERAGE AS INT) AS AGE,
    CAST(ADDRESSEMAILADDRESS AS VARCHAR(255)) AS EMAIL,
    CAST(PASSENGERISLEADPASSENGER AS BOOLEAN) AS IS_LEAD_PASSENGER,
    CAST(PASSENGERTYPENAME AS VARCHAR(100)) AS PASSENGER_TYPE_NAME,
    CAST(NATIONALITYTYPENAME AS VARCHAR(100)) AS NATIONALITY,
    INGESTION_TIMESTAMP::DATE AS INGESTION_TIMESTAMP
FROM passenger_changes
{% if is_incremental() %}
WHERE INGESTION_TIMESTAMP > (SELECT MAX(INGESTION_TIMESTAMP) FROM {{ this }})
{% endif %}
QUALIFY ROW_NUMBER() OVER (
        PARTITION BY
        SMC_PASSENGER_ID,
        DATE_TRUNC('DAY', INGESTION_TIMESTAMP)
        ORDER BY
            INGESTION_TIMESTAMP DESC
) = 1
