{{ iceberg_model_config(
    materialized_type="incremental", 
    unique_key=["OPTION_ID", "INGESTION_TIMESTAMP"],
    incremental_strategy="merge"
) }}

WITH option_scd AS (
    SELECT 
        SERVICEOPTIONINSERVICEID,
        SERVICETYPEOPTIONNAME,
        INGESTION_TIMESTAMP 
    FROM {{ source('TS', 'BOOKED_OPTION_DETAILS') }}
    WHERE SERVICEOPTIONINSERVICEID IS NOT NULL
    AND INGESTION_TIMESTAMP IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
            PARTITION BY SERVICEOPTIONINSERVICEID, SERVICETYPEOPTIONNAME
            ORDER BY INGESTION_TIMESTAMP
        )  = 1 
)
SELECT 
    CAST(SERVICEOPTIONINSERVICEID AS VARCHAR(50)) AS OPTION_ID,
    SERVICETYPEOPTIONNAME AS OPTION_NAME,
    CAST(INGESTION_TIMESTAMP AS DATE) AS INGESTION_TIMESTAMP
FROM option_scd
{% if is_incremental() %}
    WHERE INGESTION_TIMESTAMP > (SELECT MAX(INGESTION_TIMESTAMP) FROM {{ this }})
{% endif %}
QUALIFY  ROW_NUMBER() OVER (
        PARTITION BY SERVICEOPTIONINSERVICEID , DATE_TRUNC('DAY', INGESTION_TIMESTAMP)
        ORDER BY INGESTION_TIMESTAMP DESC
    )  = 1
