{{ iceberg_model_config() }}

SELECT 
    OPTION_ID,
    OPTION_NAME,
    CAST(INGESTION_TIMESTAMP AS DATE) AS EFFECTIVE_DATE,
    CAST(LEAD(INGESTION_TIMESTAMP) OVER (
        PARTITION BY OPTION_ID
        ORDER BY INGESTION_TIMESTAMP 
    ) AS DATE) AS EXPIRATION_DATE,
    CASE 
        WHEN LEAD(CAST(INGESTION_TIMESTAMP AS DATE)) OVER (
            PARTITION BY OPTION_ID
            ORDER BY INGESTION_TIMESTAMP 
        ) IS NULL THEN TRUE 
        ELSE FALSE 
    END AS IS_CURRENT
FROM {{ ref('stg_dim_option') }}

{% if is_incremental() %}
WHERE INGESTION_TIMESTAMP > (SELECT MAX(INGESTION_TIMESTAMP) FROM {{ this }})
{% endif %}

ORDER BY OPTION_ID, EFFECTIVE_DATE