{{ iceberg_model_config() }}

SELECT  
    SMC_PASSENGER_ID,
    PASSENGER_ID,
    FIRST_NAME,
    LAST_NAME,
    AGE,
    EMAIL,
    IS_LEAD_PASSENGER,
    PASSENGER_TYPE_NAME,
    NATIONALITY,
    CAST(INGESTION_TIMESTAMP AS DATE) AS EFFECTIVE_DATE,
    CAST(LEAD(INGESTION_TIMESTAMP) OVER (
        PARTITION BY SMC_PASSENGER_ID 
        ORDER BY INGESTION_TIMESTAMP
    ) AS DATE) AS EXPIRATION_DATE,
    CASE 
        WHEN LEAD(CAST(INGESTION_TIMESTAMP AS DATE)) OVER (
            PARTITION BY SMC_PASSENGER_ID 
            ORDER BY INGESTION_TIMESTAMP
        ) IS NULL THEN TRUE 
        ELSE FALSE 
    END AS IS_CURRENT
FROM {{ ref('stg_dim_passenger') }}

{% if is_incremental() %}
WHERE INGESTION_TIMESTAMP > (SELECT MAX(INGESTION_TIMESTAMP) FROM {{ this }})
{% endif %}
