{{ iceberg_model_config() }}

SELECT 
    SERVICE_ID,
    SERVICE_TYPE_NAME,
    SERVICE_LONG_NAME,
    SUPPLIER_NAME,
    SERVICE_CATEGORY,
    IS_HOTEL,
    IS_MOBILITY_SERVICE,
    IS_EXPERIENCE,
    CAST(INGESTION_TIMESTAMP AS DATE) AS EFFECTIVE_DATE ,
    CAST(LEAD(INGESTION_TIMESTAMP) OVER (
        PARTITION BY SERVICE_ID 
        ORDER BY INGESTION_TIMESTAMP
    ) AS DATE) AS EXPIRATION_DATE,
    CASE 
        WHEN LEAD(CAST(INGESTION_TIMESTAMP AS DATE)) OVER (
            PARTITION BY SERVICE_ID 
            ORDER BY INGESTION_TIMESTAMP
        ) IS NULL THEN TRUE 
        ELSE FALSE 
    END AS IS_CURRENT
  
FROM {{ ref('stg_dim_service') }}

{% if is_incremental() %}
WHERE INGESTION_TIMESTAMP > (SELECT MAX(INGESTION_TIMESTAMP) FROM {{ this }})
{% endif %}
